openapi: 3.0.0
info:
  title: DevCamper Api
  contact: {}
  version: '1.0'
servers:
- url: https://nice-jade-dolphin-hat.cyclic.app/api/v1
  variables: {}
- url: http://localhost:5000/api/v1/auth/resetpassword
  variables: {}
paths:
  /bootcamps:
    get:
      tags:
      - Bootcamps
      summary: GET All Bootcamps
      operationId: GETAllBootcamps
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://nice-jade-dolphin-hat.cyclic.app/api/v1
        variables: {}
    post:
      tags:
      - Bootcamps
      summary: Create a Bootcamp
      operationId: CreateaBootcamp
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/CreateaBootcampRequest'
              - example:
                  name: js masteryg
                  description: Is coding your passion? Codemasters will give you the skills and the tools to become the best developer possible. We specialize in full stack web development and data science
                  website: https://codemasters.com
                  phone: (333) 333-3333
                  email: enroll@codemasters.com
                  address: 85 South Prospect Street Burlington VT 05405
                  careers:
                  - Web Development
                  - Data Science
                  - Business
                  housing: false
                  jobAssistance: false
                  jobGuarantee: false
                  acceptGi: false
            example:
              name: js masteryg
              description: Is coding your passion? Codemasters will give you the skills and the tools to become the best developer possible. We specialize in full stack web development and data science
              website: https://codemasters.com
              phone: (333) 333-3333
              email: enroll@codemasters.com
              address: 85 South Prospect Street Burlington VT 05405
              careers:
              - Web Development
              - Data Science
              - Business
              housing: false
              jobAssistance: false
              jobGuarantee: false
              acceptGi: false
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://nice-jade-dolphin-hat.cyclic.app/api/v1
        variables: {}
  /bootcamps/{bootcampId}:
    parameters:
      - in: path
        name: bootcampId
        schema:
          type: string
        required: true
        description: The Bootcamp ID
    get:
      tags:
      - Bootcamps
      summary: Get Single Bootcamp
      operationId: GetSingleBootcamp
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://nice-jade-dolphin-hat.cyclic.app/api/v1
        variables: {}
 
    put:
      tags:
      - Bootcamps
      summary: Update a bootcamp
      operationId: Updateabootcamp
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/UpdateabootcampRequest'
              - example:
                  name: Codlle Mastere
                  description: Is coding your passion? Codemasters will give you the skills and the tools to become the best developer possible. We specialize in full stack web development and data science
                  website: https://codemasters.com
                  phone: (333) 333-3333
                  email: enroll@codemasters.com
                  address: 85 South Prospect Street Burlington VT 05405
                  careers:
                  - Web Development
                  - Data Science
                  - Business
                  housing: false
                  jobAssistance: false
                  jobGuarantee: false
                  acceptGi: false
            example:
              name: Codlle Mastere
              description: Is coding your passion? Codemasters will give you the skills and the tools to become the best developer possible. We specialize in full stack web development and data science
              website: https://codemasters.com
              phone: (333) 333-3333
              email: enroll@codemasters.com
              address: 85 South Prospect Street Burlington VT 05405
              careers:
              - Web Development
              - Data Science
              - Business
              housing: false
              jobAssistance: false
              jobGuarantee: false
              acceptGi: false
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://nice-jade-dolphin-hat.cyclic.app/api/v1
        variables: {}
  
    delete:
      tags:
      - Bootcamps
      summary: Delete a Bootcamp
      operationId: DeleteaBootcamp
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://nice-jade-dolphin-hat.cyclic.app/api/v1
        variables: {}
  /bootcamps/radius/05405/10:
    get:
      tags:
      - Bootcamps
      summary: Get Bootcamp by radius
      operationId: GetBootcampbyradius
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://nice-jade-dolphin-hat.cyclic.app/api/v1
        variables: {}
  /bootcamps/5d713a66ec8f2b88b8f830b8/photo:
    put:
      tags:
      - Bootcamps
      summary: Upload Photo
      operationId: UploadPhoto
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding: {}
            schema:
              required:
              - file
              type: object
              properties:
                file:
                  type: string
        required: false
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://nice-jade-dolphin-hat.cyclic.app/api/v1
        variables: {}
  /courses:
    get:
      tags:
      - Courses
      summary: Get Courses
      operationId: GetCourses
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://nice-jade-dolphin-hat.cyclic.app/api/v1
        variables: {}
  /bootcamps/5d713995b721c3bb38c1f5d0/courses:
    get:
      tags:
      - Courses
      summary: Get courses for bootcamp
      operationId: Getcoursesforbootcamp
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://nice-jade-dolphin-hat.cyclic.app/api/v1
        variables: {}
    post:
      tags:
      - Courses
      summary: Create Course
      operationId: CreateCourse
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/CreateCourseRequest'
              - example:
                  title: Web Design & Development 2 3
                  description: Get started building websites and web apps with HTML/CSS/JavaScript/PHP. We teach you
                  weeks: 10
                  tuition: 12000
                  minimumSkill: beginner
                  scholarhipsAvailable: true
            example:
              title: Web Design & Development 2 3
              description: Get started building websites and web apps with HTML/CSS/JavaScript/PHP. We teach you
              weeks: 10
              tuition: 12000
              minimumSkill: beginner
              scholarhipsAvailable: true
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://nice-jade-dolphin-hat.cyclic.app/api/v1
        variables: {}
  /courses/5d725c84c4ded7bcb480eaa0:
    get:
      tags:
      - Courses
      summary: Get single course
      operationId: Getsinglecourse
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://nice-jade-dolphin-hat.cyclic.app/api/v1
        variables: {}
  /courses/5d725a4a7b292f5f8ceff789:
    put:
      tags:
      - Courses
      summary: Update Course
      operationId: UpdateCourse
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/UpdateCourseRequest'
              - example:
                  weeks: '10'
                  tuition: 9000
            example:
              weeks: '10'
              tuition: 9000
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://nice-jade-dolphin-hat.cyclic.app/api/v1
        variables: {}
    delete:
      tags:
      - Courses
      summary: Delete Course
      operationId: DeleteCourse
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://nice-jade-dolphin-hat.cyclic.app/api/v1
        variables: {}
  /auth/register:
    post:
      tags:
      - Auth
      summary: Register user
      operationId: Registeruser
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/RegisteruserRequest'
              - example:
                  name: noor
                  email: noor@gmail.com
                  role: admin
                  password: noor011
            example:
              name: noor
              email: noor@gmail.com
              role: admin
              password: noor011
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://nice-jade-dolphin-hat.cyclic.app/api/v1
        variables: {}
  /auth/login:
    post:
      tags:
      - Auth
      summary: Login user
      operationId: Loginuser
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/LoginuserRequest'
              - example:
                  email: noor@gmail.com
                  password: noor011
            example:
              email: noor@gmail.com
              password: noor011
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://nice-jade-dolphin-hat.cyclic.app/api/v1
        variables: {}
  /auth/me:
    get:
      tags:
      - Auth
      summary: Get logged in user info
      operationId: Getloggedinuserinfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://nice-jade-dolphin-hat.cyclic.app/api/v1
        variables: {}
  /auth/forgotpassword:
    post:
      tags:
      - Auth
      summary: Reset Password
      operationId: ResetPassword
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/ResetPasswordRequest'
              - example:
                  email: nayanrahman51@gmail.com
            example:
              email: nayanrahman51@gmail.com
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://nice-jade-dolphin-hat.cyclic.app/api/v1
        variables: {}
  /930181dc179b7488bb5d8a36e21fc08786bc2089:
    put:
      tags:
      - Auth
      summary: Update Password
      operationId: UpdatePassword
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/UpdatePasswordRequest'
              - example:
                  password: 123456
            example:
              password: 123456
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: http://localhost:5000/api/v1/auth/resetpassword
        variables: {}
  /users:
    get:
      tags:
      - Admin
      summary: Get All Users
      operationId: GetAllUsers
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://nice-jade-dolphin-hat.cyclic.app/api/v1
        variables: {}
    post:
      tags:
      - Admin
      summary: Create A user
      operationId: CreateAuser
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/CreateAuserRequest'
              - example:
                  name: noor
                  email: noor@gmail.com
                  role: admin
                  password: noor011
            example:
              name: noor
              email: noor@gmail.com
              role: admin
              password: noor011
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://nice-jade-dolphin-hat.cyclic.app/api/v1
        variables: {}
  /users/5c8a1d5b0190b214360dc038:
    get:
      tags:
      - Admin
      summary: Get Single User
      operationId: GetSingleUser
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://nice-jade-dolphin-hat.cyclic.app/api/v1
        variables: {}
    put:
      tags:
      - Admin
      summary: Update User
      operationId: UpdateUser
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/UpdateUserRequest'
              - example:
                  role: admin
            example:
              role: admin
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://nice-jade-dolphin-hat.cyclic.app/api/v1
        variables: {}
    delete:
      tags:
      - Admin
      summary: Delete a user
      operationId: Deleteauser
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://nice-jade-dolphin-hat.cyclic.app/api/v1
        variables: {}
  /:
    get:
      tags:
      - Revies
      summary: Get All Reviews
      description: Getting all the reviews
      operationId: GetAllReviews
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /bootcamps/63c03fc2d7b5a1a69260f07c/reviews:
    get:
      tags:
      - Revies
      summary: Get Bootcamp Reviews
      description: Bootcamp Reivew
      operationId: GetBootcampReviews
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://nice-jade-dolphin-hat.cyclic.app/api/v1
        variables: {}
  /reviews/5d7a514b5d2c12c7449be025:
    get:
      tags:
      - Revies
      summary: Get Single Review
      operationId: GetSingleReview
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      servers:
      - url: https://nice-jade-dolphin-hat.cyclic.app/api/v1
        variables: {}
components:
  schemas:
    CreateaBootcampRequest:
      title: CreateaBootcampRequest
      required:
      - name
      - description
      - website
      - phone
      - email
      - address
      - careers
      - housing
      - jobAssistance
      - jobGuarantee
      - acceptGi
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        website:
          type: string
        phone:
          type: string
        email:
          type: string
        address:
          type: string
        careers:
          type: array
          items:
            type: string
          description: ''
        housing:
          type: boolean
        jobAssistance:
          type: boolean
        jobGuarantee:
          type: boolean
        acceptGi:
          type: boolean
      example:
        name: js masteryg
        description: Is coding your passion? Codemasters will give you the skills and the tools to become the best developer possible. We specialize in full stack web development and data science
        website: https://codemasters.com
        phone: (333) 333-3333
        email: enroll@codemasters.com
        address: 85 South Prospect Street Burlington VT 05405
        careers:
        - Web Development
        - Data Science
        - Business
        housing: false
        jobAssistance: false
        jobGuarantee: false
        acceptGi: false
    UpdateabootcampRequest:
      title: UpdateabootcampRequest
      required:
      - name
      - description
      - website
      - phone
      - email
      - address
      - careers
      - housing
      - jobAssistance
      - jobGuarantee
      - acceptGi
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        website:
          type: string
        phone:
          type: string
        email:
          type: string
        address:
          type: string
        careers:
          type: array
          items:
            type: string
          description: ''
        housing:
          type: boolean
        jobAssistance:
          type: boolean
        jobGuarantee:
          type: boolean
        acceptGi:
          type: boolean
      example:
        name: Codlle Mastere
        description: Is coding your passion? Codemasters will give you the skills and the tools to become the best developer possible. We specialize in full stack web development and data science
        website: https://codemasters.com
        phone: (333) 333-3333
        email: enroll@codemasters.com
        address: 85 South Prospect Street Burlington VT 05405
        careers:
        - Web Development
        - Data Science
        - Business
        housing: false
        jobAssistance: false
        jobGuarantee: false
        acceptGi: false
    CreateCourseRequest:
      title: CreateCourseRequest
      required:
      - title
      - description
      - weeks
      - tuition
      - minimumSkill
      - scholarhipsAvailable
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        weeks:
          type: integer
          format: int32
        tuition:
          type: integer
          format: int32
        minimumSkill:
          type: string
        scholarhipsAvailable:
          type: boolean
      example:
        title: Web Design & Development 2 3
        description: Get started building websites and web apps with HTML/CSS/JavaScript/PHP. We teach you
        weeks: 10
        tuition: 12000
        minimumSkill: beginner
        scholarhipsAvailable: true
    UpdateCourseRequest:
      title: UpdateCourseRequest
      required:
      - weeks
      - tuition
      type: object
      properties:
        weeks:
          type: string
        tuition:
          type: integer
          format: int32
      example:
        weeks: '10'
        tuition: 9000
    RegisteruserRequest:
      title: RegisteruserRequest
      required:
      - name
      - email
      - role
      - password
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        role:
          type: string
        password:
          type: string
      example:
        name: noor
        email: noor@gmail.com
        role: admin
        password: noor011
    LoginuserRequest:
      title: LoginuserRequest
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: noor@gmail.com
        password: noor011
    ResetPasswordRequest:
      title: ResetPasswordRequest
      required:
      - email
      type: object
      properties:
        email:
          type: string
      example:
        email: nayanrahman51@gmail.com
    UpdatePasswordRequest:
      title: UpdatePasswordRequest
      required:
      - password
      type: object
      properties:
        password:
          type: integer
          format: int32
      example:
        password: 123456
    CreateAuserRequest:
      title: CreateAuserRequest
      required:
      - name
      - email
      - role
      - password
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        role:
          type: string
        password:
          type: string
      example:
        name: noor
        email: noor@gmail.com
        role: admin
        password: noor011
    UpdateUserRequest:
      title: UpdateUserRequest
      required:
      - role
      type: object
      properties:
        role:
          type: string
      example:
        role: admin
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
- name: Bootcamps
- name: Courses
- name: Auth
- name: Admin
- name: Revies
